/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asvsapp;

import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

public class app {
   
    public static void main(String[] args) {
        System.out.println("Main Class reads the json file");
        
        // create Gson instance
        Gson gson = new Gson();
        //JsonReader.setLenient(true);

    try {
    
        Path pathToFile = Paths.get("app/src/main/resources/referenceData/GoldenData.json");

        // create a reader
        Reader reader = Files.newBufferedReader(pathToFile.toAbsolutePath());
    
        // convert JSON file to map
        Map<?, ?> map = gson.fromJson(reader, Map.class);
    
        // print map entries
        for (Map.Entry<?, ?> entry : map.entrySet()) {
            System.out.println(entry.getKey() + "=" + entry.getValue());
        }
    
        // close reader
        reader.close();
    
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

}
