/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asvsapp;

import java.io.IOException;

public class app {

    public static void main(String[] args) throws IOException {

         asvsapp.igloo.parseIglooData.praseJsonLine();
         asvsapp.csvWrite.csvWriteResults.writeResultData();
        

        //  asvsapp.amp.getAmpBestMatch.getJsonBestMatch(null);

    }
}
