# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
#     - name: Build with Gradle
#       uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#       with:
#         arguments: build
#       run: ./gradlew build 
      
#     - name: Run Jar
#       run: java -jar app/build/libs/app.jar
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::219619990026:role/ihr-algolia-validation
        aws-region: us-east-1
        
    - name: Download Igloo Json Data File from S3 bucket
      run: |
        aws s3 cp s3://ihr-de-stg-prod/search_golden_dataset/top_search_terms/dt=2022-11-14/000.json app/src/main/resources/InputData/ 
      
              
#     - name: Download Igloo Json Data File from S3 bucket1
#       run: |
#         aws s3 ls s3://ihr-de-stg-prod/search_golden_dataset/top_search_terms/dt=2022-11-14/